### ISSUE TITLE
Commands to be implemented

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#10]
Do we want to avoid all `WARNING: unrecognized command/environment`, or are some of these essentially harmless? In any case, here are a few which appear right now in the Stacks project.

- [x] `\romannumeral`
- [ ] `\hrulefill`

**Comment by PatrickMassot** [comment]
I'm very surprised ``\max`` is not recognized. Or are you trying to use ``\max`` outside math mode?

Do you have a minimal example?

**Comment by pbelmans** [comment]
I was also surprised, but I saw it coming by in the output when running it on the entire Stacks project. I'll look into it at some point, I was just collecting things in a not very systematical way.

**Comment by pbelmans** [comment]
Ignore `\max`, it's a default renderer warning, not an unrecognized command/environment.

**Comment by pbelmans** [comment]
Commit 4dbe830d5f383ec2b523041dc65ed29003873149 implements `\romannumeral`.
