### ISSUE TITLE
Fix TeXFragment in labels

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#13]
Currently we use the `.paux` file generated by plasTeX to read off the names of named propositions etc. But the way we reconstruct the context gives issues when there are accents involved, resulting in `plasTeX.TeXFragment` in the output. This is just a silly thing but I haven't looked at the Pickle documentation so far to figure out how it should work.

This issue might be better in the `gerby-tools` repository, but I'll put it here to keep things centralised.

**Comment by pbelmans** [comment]
Actually, maybe it _is_ an issue with plasTeX: `Macro.persist` tries to take care of objects, but it doesn't do anything special with `TeXFragment`.

**Comment by pbelmans** [comment]
Unless I'm missing something obvious, there is an issue with the `title` field in the `persist` method of a Macro: it is <em>already</em> converted to a string, but in the wrong way, so that it reads `'<plasTeX.TeXFragment object at 0x10c317108>'` whenever it wasn't obviously a string. This happens when there accents in the title of a section, or the caption of a theorem.

So it seems that this issue is caused by an internal plasTeX bug, not by me abusing the `paux` file (in particular, it's *not* a Pickle issue).

**Comment by pbelmans** [comment]
I just checked with the HTML5 renderer, and there the `title` field is also wrong. So somewhere there is a weird conversion to a string happening.

**Comment by PatrickMassot** [comment]
I'm not sure what you are talking about, could you describe how to reproduce this problem?

**Comment by pbelmans** [comment]
Of course, I should've done this in the beginning, sorry. I'm now not in a position to produce a minimal working example and test it in a fresh clone of plasTeX, but the problem appears for me when looking at the theorems with captions that contain accents. The following is taken from tag 07MM, which is one of the tags that go wrong.

```latex
\begin{remark}[{\v C}ech complex]
...
\end{remark}
```

Already in the HTML5 output it says `TeXFragment` where the title is displayed.

**Comment by PatrickMassot** [comment]
I'm sorry, it was all my fault. I made a [PR upstream](https://github.com/tiarno/plastex/pull/94).

Funny thing is I didn't come across this bug while my native language does use accents. This is unicode power! (I would never write anything like {\v C}ech in a LaTeX file nowadays, but rather go for  Čech).

**Comment by PatrickMassot** [comment]
Note that the time I used to write the previous comment was slightly more than the time @kesmit13 used to merge the upstream PR!

**Comment by pbelmans** [comment]
Thanks for figuring this out, and fixing this!

~~Now my challenge is to figure out how to merge this properly in the `gerby` branch in my own clone.~~ _Done_
