### ISSUE TITLE
User-defined enumeration of lists

### ISSUE THREAD

**Issue by chngr** [gerby-project/plastex#14]
Custom enumerations of lists are currently ignored. For instance, in 07EZ, the second enumerate environment is written in the LaTeX source as
```
\begin{enumerate}
\item[(a)] (4) $\Rightarrow$ (3) $\Rightarrow$ (2) $\Rightarrow$ (1),
\item[(b)] (6) $\Rightarrow$ (5),
\item[(c)] (6) $\Rightarrow$ (4),
\item[(d)] (5) $\Rightarrow$ (2),
\item[(e)] (2) $\Rightarrow$ the elements $a^e$, $e \geq e_0$ are
strictly standard in $A$ over $R$,
\item[(f)] (4) $\Rightarrow$ the elements $a^e$, $e \geq e_0$ are
elementary standard in $A$ over $R$.
\end{enumerate}
```
but the HTML output is simply
```
<ol>
  <li><p>(4) $\Rightarrow $ (3) $\Rightarrow $ (2) $\Rightarrow $ (1), </p>
</li>
<li><p>(6) $\Rightarrow $ (5), </p>
</li>
<li><p>(6) $\Rightarrow $ (4), </p>
</li>
<li><p>(5) $\Rightarrow $ (2), </p>
</li>
<li><p>(2) $\Rightarrow $ the elements $a^ e$, $e \geq e_0$ are strictly standard in $A$ over $R$, </p>
</li>
<li><p>(4) $\Rightarrow $ the elements $a^ e$, $e \geq e_0$ are elementary standard in $A$ over $R$. </p>
</li>

</ol> 
```
making the list enumeration simply the default arabic enumeration. This is confusing since the proof makes reference to the alphabetical enumeration in the second list.

**Comment by PatrickMassot** [comment]
This is purely a template issue (also in HTML5, I should fix that at some point). In ``renderer/Gerby/Lists.jinja2``, you could change:
```html
name: item
<li>{{ obj }}</li>
```
to
```html
name: item
<li>{% if obj.attributes['term'] %}<span class="item-term">{{ obj.attributes['term'] }}</span>{% endif %}{{ obj }}</li>
```

**Comment by pbelmans** [comment]
Thanks!

Reminder to myself: when I start implementing this, it is probably easier on a purely styling-technical level to put the value as an attribute on the `<li>` itself, because then the `:content` property can read off that attribute.
