### ISSUE TITLE
Equation numbering is different

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#15]
Whilst looking at #8 I discovered that plasTeX currently numbers things differently compared to the Stacks project. We should figure out how to incorporate the (sub)sections into the equation numbering.

This could very well be already in plasTeX, I'm just recording it here.

**Comment by pbelmans** [comment]
On the other hand, `numberwithin` does not appear anywhere in the source code. So this might as well be a missing feature.

**Comment by PatrickMassot** [comment]
This amsmath macro is not implemented currently, but it shouldn't be hard. I could do it at some point if you don't do it before.

**Comment by pbelmans** [comment]
I won't be near a computer this weekend, so go ahead if you want to. Otherwise I will do it next week.

**Comment by PatrickMassot** [comment]
I made a [pull request](https://github.com/tiarno/plastex/pull/96) upstream.

**Comment by PatrickMassot** [comment]
Upstream PR was merged, you can pull. You should probably read the code if you never looked at how plasTeX deals with counters.
