### ISSUE TITLE
MathJax and XyJax Issues via Headless Browser

### ISSUE THREAD

**Issue by chngr** [gerby-project/plastex#21]
Answering the first comment in #18, we have now implemented a headless browser test in `gerby-website` to look for MathJax and XyJax issues; see commits [74ec25f](https://github.com/pbelmans/gerby-website/commit/74ec25f2ae12404f3a3cfe7078dd9e89736874cd) and [fae866d](https://github.com/pbelmans/gerby-website/commit/fae866d13207ac513c41bf8a5391289baf6e74ea).

I have run the tests today and have found the following issues, all of which are present on `mercer`:
- [x] 1. `xymatrix` pictures in Tags [00RM](http://mercer.math.columbia.edu:20000/tag/00RM), [08RM](http://mercer.math.columbia.edu:20000/tag/08RM), [04BL](http://mercer.math.columbia.edu:20000/tag/04BL); this has to do with new lines `\\` in `xymatrix` taking in `[..]` as spacing.
- [x] 2. Funny enough, [Tag 018I](http://mercer.math.columbia.edu:20000/tag/018I); turns out MathJax does not implement `\relax`. Note that, as of writing, this is also an issue on the live version of the Stacks Project, see [here](https://stacks.math.columbia.edu/tag/018I).
- [x] 3. In Tags [0347](http://mercer.math.columbia.edu:20000/tag/0347), [036F](http://mercer.math.columbia.edu:20000/tag/036F), [03DR](http://mercer.math.columbia.edu:20000/tag/03DR), [02YD](http://mercer.math.columbia.edu:20000/tag/02YD), [04MM](http://mercer.math.columbia.edu:20000/tag/04MM), [03X7](http://mercer.math.columbia.edu:20000/tag/03X7), [04I4](http://mercer.math.columbia.edu:20000/tag/04I4), [06EN](http://mercer.math.columbia.edu:20000/tag/06EN), [044Y](http://mercer.math.columbia.edu:20000/tag/044Y), [06X7](http://mercer.math.columbia.edu:20000/tag/06X7), [072F](http://mercer.math.columbia.edu:20000/tag/072F), and [076N](http://mercer.math.columbia.edu:20000/tag/076N). For some reason, MathJax is not happy with the `\linebreak` command, although it seems to work fine on the live Stacks Project.
- [x] 4. In the first displaymath in Tag [08WE](http://mercer.math.columbia.edu:20000/tag/08WE), and also in an `xymatrix` down the page in Tag [08X7](http://mercer.math.columbia.edu:20000/tag/08X7). There are again unicode endashes, so somehow, plasTeX is not recognizing the entire `{...}` chunk as the argument to an `xymatrix`. In the second one, I think this might have to do with the funny configuration `\xymatrix@C=8pc{...}`, so that it thinks `@C=pc` is the argument to `\xymatrix`. In the first case, it might have something to do with the use of `@`, but I don't know.
- [x] 5. In Tag [02QD](http://mercer.math.columbia.edu:20000/tag/02QD), there is an `align*` environment in the middle which is not rendering. This is due to the plasTeX output: it does not add whitespace for a newline. As a consequence, the TeX code looks like `... h [t_1, \ldots , t_ a] \\[s_1, \ldots , s_ b]...`. Now, in the `align*` environment, `[..]` after the newline `\\` character is meant to specify the size of the line break, so the input of more TeX code will throw an error.
- [x] 6. In Tags [0B9X](http://mercer.math.columbia.edu:20000/tag/0B9X), and [0DP6](http://mercer.math.columbia.edu:20000/tag/0DP6), there are parsing errors in `xymatrix` diagrams. In fact, both of these happen on the live Stacks Project, see [here](https://stacks.math.columbia.edu/tag/0B9X) and [here](https://stacks.math.columbia.edu/tag/0DP6). Both of these are due to XyJax issues: for some reason, XyJax cannot handle `{\rm ...}`; replacing this by, say, `\mathrm{...}` fixes the issue.
- [x] 7. In Tag [0BG1](http://mercer.math.columbia.edu:20000/tag/0BG1), there is a parse error in the second `\xymatrix`. In fact, this happens on the live Stacks Project, [here](https://stacks.math.columbia.edu/tag/0BG1). I have tinkered with it, and the culprit might be that `\ldots` is not implemented in XyJax, although I am not completely sure---the diagram renders if you remove `\ldots`.
- [x] 8. In Tag [03UD](http://mercer.math.columbia.edu:20000/tag/03UD), the `xymatrix` does not parse. This also happens on the live Stacks Project, [here](https://stacks.math.columbia.edu/tag/03UD). With some tinkering, the problem seems to lie in the hookarrow: XyJax does not appear to like `\ar@{^(->}`. In particular, it does not like the caret. Removing even just the caret makes it render.
- [x] 9. In Tag [0CUZ](http://mercer.math.columbia.edu:20000/tag/0CUZ), the `xymatrix` in the statement does not parse. This is also true on the live Stacks Project, [here](https://stacks.math.columbia.edu/tag/0CUZ). After tinkering, I believe the issue is a terrible bug in XyJax: you cannot write `\ar[d] v` and, instead, must write `v \ar[d]`. That is, all your diagram entries must come before the `\ar` command. At least, splitting the big displaymath into three, each containing exactly one of the `xymatrix` diagrams shows that only the second one causes an error; then changing the lone instance `\ar[l] v` there fixes the issue.
- [x] 10. In Tag [0CWC](http://mercer.math.columbia.edu:20000/tag/0CWC), the two `xymatrix` diagrams do not render. This is also true on the live Stacks Project, [here](https://stacks.math.columbia.edu/tag/0CWC). The issue is the same as above: in the two diagrams, there are patterns like `\ar[..] <something> ...` and changing it so that `<something>` is on the left of the `\ar` commands fixes it. Dammit XyJax!
- [x] 11. In Tag [0D5R](http://mercer.math.columbia.edu:20000/tag/0D5R), the `xymatrix` in the statement does not render. This is also true on the live Stacks Project, [here](https://stacks.math.columbia.edu/tag/0D5R). The issue appears to be that XyJax does not know how to parse the pattern `{}` that appears in the beginning of this `xymatrix`---removing it or changing it to some character fixes the problem.
- [x] 12. In Tag [076P](http://mercer.math.columbia.edu:20000/tag/076P), the last `xymatrix` on the page fails to render. This is due to the `\drtwocell <\omit >{<-2>\varphi }` part. There is an extra space in the command `<\omit>` and that extra space is causing the error. This is somehow coming from the plasTeX parsing.

I believe these are all for now. Many of these issues are actually things not related to plasTeX and are ideally resolved by patching XyJax. In any case, even if we do not feel like patching XyJax ourselves, it may be good to note that these are issues there.

**Comment by chngr** [comment]
Items 1, 4, 5, and 12 are addressed in the commits made in #22. Some notes:
- Turns out 1 had nothing to do with the `xymatrix` environment; rather, some whitespace after the newline character `\\` was unwisely devoured by plasTeX, hence bringing the patterns `[...]` to arguments for the newline spacing. This is fixed by adding an option in the argument string of macros to turn on the (previously unused) parsing flag to stop whitespace from being automatically stripped.
- Issue 4 had to do with how plasTeX tokenizes macros. Quite reasonably, the entire pattern `\xymatrix@C` was treated as the macro name in `\xymatrix@C=8pc{...}`, so the argument was not parsed in the `NoCharSub` environment. A sort of not-so-pretty fix is to add a macro to `xy.py` for each of the possible `\xymatrix@*`, where the `*` is filled in with the possibilities described in section 3.3 of the [XY-pic User's Guide](http://mirrors.rit.edu/CTAN/macros/generic/diagrams/xypic/doc/xyguide.pdf).

**Comment by chngr** [comment]
Issue 2 was directly addressed on the Stacks Project in commit [38740bf](https://github.com/stacks/stacks-project/commit/38740bf9966d9f2f846b73422b75cbe4f64d3bb1).

**Comment by chngr** [comment]
Item 3 is fixed by commit [532e0ee](https://github.com/pbelmans/gerby-website/pull/10/commits/532e0ee438543b4ea5677205f268c55507b74d25).

**Comment by chngr** [comment]
Issues 6, 9, and 10 are dealt with in pull request [#50](https://github.com/stacks/stacks-project/pull/50) over at the Stacks Project.

**Comment by aisejohan** [comment]
Commit https://github.com/stacks/stacks-project/commit/a355c4290db17ac867a474c4ee5ce6628d4ba49b  fixes 7, 8 but not 11 (kinda as expected because of what you said the problem was...) in the live version of the stacks project

**Comment by pbelmans** [comment]
@chngr, @aisejohan Is there a reason why we haven't fixed item 11? Both of you understand XyJax issues much better than I do, so I figured I'd ask first before spending 2 hours on fixing it.

**Comment by chngr** [comment]
I think we concluded that we don't know how to change the source code while keeping the same diagram. I think my comment already indicated what is the issue.

**Comment by pbelmans** [comment]
You get a visually indistinguishable diagram by using `\,`, I just checked it locally.

**Comment by aisejohan** [comment]
Sorry, I do not understand: Do you mean put `\,` before `{}`?

**Comment by pbelmans** [comment]
No, replace. You are using` {}` as something invisible to attach the sub and superscript to. But this makes XyJax confused. So I suggest to use `\,` as the invisible thing to attach the sub and superscript to. It's slightly less invisible as it takes up a non-zero amount of whitespace, but that doesn't matter for the output, unless you have an extremely strong typographical eye.

**Comment by aisejohan** [comment]
OK! Just made the change in the Stacks project. We'll see if it works on the server later today and then we can close this issue.

**Comment by aisejohan** [comment]
This issue can be closed now, but I do not have the permissions to do so it seems...
