### ISSUE TITLE
Check that every tag actually appears in the document

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#25]
There should at least be a warning when this is not the case.

**Comment by pbelmans** [comment]
Travis is giving lots of

    WARNING: document does not contain tag 0003

see https://api.travis-ci.org/v3/job/375339121/log.txt. Is this expected behaviour?

**Comment by chngr** [comment]
Nope. Strange. It seemed to work for me locally. I'll debug it.

**Comment by chngr** [comment]
Ohp. Looks like I partially changed some variable names just after I tested and before I pushed. Testing again and then this should be okay.

**Comment by pbelmans** [comment]
Good to have Travis then :). Too bad it goes overtime so often.

**Comment by chngr** [comment]
Fixed again via 9c510b6.
