### ISSUE TITLE
Don't render apostrophes

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#37]
`Krull's intersection theorem` is rendered as `Krull’s intersection theorem` making the search function bork.

**Comment by pbelmans** [comment]
So this is dealt by the list `charsubs` defined in `plasTeX/__init__.py`.

**Comment by aisejohan** [comment]
Not sure if this is related but in mathematics on tag `0D2I` the double prime on `\mathfrak b` doesn't look like a prime to me. Maybe this is not a plastex but rather a gerby-website issue?

**Comment by pbelmans** [comment]
Nope, this is a plasTeX issue: it shouldn't apply accents when in math mode, as we let MathJax handle these. If you feed MathJax the processed double primes, it cannot give good output.

Easy solution: just disable double prime accents altogether. Harder solution: only disable them in math mode. I'll see what I can do. I'm reopening for now.
