### ISSUE TITLE
XyJax parsing errors

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#5]
If we want to stick with MathJax and XyJax, then we better fix 039P, ~~054L~~, 00HU. It should suffice to compare the outputted code, and see what's different. One possibility is plasTeX's habit of inserting spaces before underscores, but there could be other reasons.

**Comment by maxlieblich** [comment]
It appears that these are all caused by plastex parsing errors.

**Comment by pbelmans** [comment]
They are, but 054L is of a different nature than 039P, see #6.

We should try to figure out which tags give an XyJax error in some automated way. @maxlieblich Do you have a good way of doing this?

**Comment by pbelmans** [comment]
Possible explanation: `\mathop` isn't handled appropriately, and stops and restarts the math rendering. I will look into this.

**Comment by pbelmans** [comment]
At least one of the things that goes wrong is the `\ar@`.

**Comment by pbelmans** [comment]
I just took a look at the `xypic` documentation. Its syntax is peculiar, to say the least. Is it possible to let everything inside an `\xymatrix` just be unhandled by the parser?

This will also be necessary if we want to have some tool converting `xypic` to SVG. Right now, the `.source` attribute just doesn't contain the right source.
