### ISSUE TITLE
\texorpdfstring isn't implemented

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#50]
`\textorpdfstring` is implemented, but that is wrong. Also, there is no template.

**Comment by chngr** [comment]
The incorrect `\texorpdfstring` in`hyperref.py` is fixed in b781272. The corresponding template is implemented in d1c5389.

**Comment by pbelmans** [comment]
Isn't the implementation of the template a bit too naive? In both the `tex` and the `pdfstring` part there could be `{}`'s and hence `}{`'s appearing.

**Comment by chngr** [comment]
Yup, you're right. I made it a bit less naïve in fe41b6d, upon adding more access to arguments of commands in 4b36f93.
