### ISSUE TITLE
\ref in \text commands in \matrix

### ISSUE THREAD

**Issue by chngr** [gerby-project/plastex#52]
So `\ref` has no reason to work in mathematics commands like `\matrix`: the template for the latter will just print out the raw LaTeX source, as it reasonably should, and so the plasTeX entity corresponding to this `\ref` should be completely lost.

For a test case, see tag [07JH](https://stacks-test.math.columbia.edu/tag/07JH). Miraculously, `\ref` seems to work as expected on the live version, but does not work on my local build.

**Comment by pbelmans** [comment]
We deal with these unprocessed `\ref` in `tools/update.py` in Gerby, and have been for quite some time. So it's weird that it doesn't work for you.

**Comment by chngr** [comment]
Oh great! I'll look into it a bit later on.

**Comment by pbelmans** [comment]
It's not an issue on the current live version, so I assume this never was an issue.
