### ISSUE TITLE
Make (gerby) plastex work with python 3.7

### ISSUE THREAD

**Issue by kodyvajjha** [gerby-project/plastex#57]
This is essentially issue [#109](https://github.com/tiarno/plastex/issues/109) in the upstream plastex. 

A change in Python 3.7 exception handling inside generators breaks plastex. I am opening an issue here as I am unsure if my hackish workaround (as described in the link above) is PR-worthy.

**Comment by pbelmans** [comment]
As your workaround is the one suggested in the PEP, it is definitely PR-worthy. I assume you have locally implemented the fix, if that is the case, feel free to create a pull request.

**Comment by kodyvajjha** [comment]
Just did. #58
