### ISSUE TITLE
A wild \end{matrix} has appeared

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#6]
In the proof of tag 054L, the last "commutative diagram" (which is a Jacobian matrix) has an `\end{matrix}` right after the `\begin{matrix}`. This shouldn't happen.

**Comment by chngr** [comment]
This actually happens for every instance of ``\begin{matrix}`` and ``\begin{align*}``. This might happen for other environments, too, but I have yet to find others.

I have also checked that the following environments, which appear in the code, do not behave strangely: ``\begin{equation}``, ``\begin{eqnarray}``, and ``\begin{eqnarray*}``.

**Comment by pbelmans** [comment]
Just looking around a bit I find it weird that `plasTeX/Base/LaTeX/Math.py` sets `macroName` on `eqnarray` to `None`, whilst for others environments it is to something meaningful in `plasTeX/Packages/amsmath.py`. This is my best guess so far, I'll take a look at this.

**Comment by pbelmans** [comment]
Okay, this was ridiculous of me. The package `amsmath` wasn't loaded explicitly in the LaTeX code. So plasTeX didn't realise it should do something special (i.e. just treat it as an `eqnarray`) with `align*`.

Nevertheless, we did have a template for `align*`, so it just applied that, and it didn't complain about not knowing an implementation for this environment in Python (it _does_ complain when there's no template).

This problem was related to the fact that we always change the preamble for the Stacks project, just replacing it with `book`. So the TeX file creation code should just not create an `amsbook` and we're fine, because then `\usepackage{amsmath}` is required. I think.

**Comment by pbelmans** [comment]
I haven't tested it yet on a `matrix` environment, so stay tuned whether this should actually be closed or not.

**Comment by pbelmans** [comment]
It is fixed.
