### ISSUE TITLE
Handle footnotes

### ISSUE THREAD

**Issue by pbelmans** [gerby-project/plastex#9]
This is important, and right now not taken care of at all. I hope it won't be too hard...

**Comment by PatrickMassot** [comment]
What do you mean by "not taken care of at all"? The command ``footnote`` exists and XHTML and HTML5 renderers have corresponding templates see [Footnotes.jinja2s](https://github.com/pbelmans/plastex/blob/master/plasTeX/Renderers/HTML5/Footnotes.jinja2s) for the main text mark and how the note text appears in the [default layout](https://github.com/pbelmans/plastex/blob/f07aab870059c1b548e54c0a7b17482884cc9060/plasTeX/Renderers/HTML5/Themes/default/default-layout.jinja2#L113-L121).

**Comment by pbelmans** [comment]
PlasTeX indeed has the functionality to deal with them, we just don't deal with them at the moment. We need footnotes to appear whenever they are used: if within a section 2 lemmas use a footnote, we need a footnote in the output for each each lemma, and both footnotes in the section output file.

Possible issues are:
* we need to number footnotes depending on the context, as a single footnote might need to receive multiple numbers
* what if both the statement and the proof contain a footnote? this is related to the previous issue

**Comment by pbelmans** [comment]
One possible solution is to write each footnote to a file, like we do for all tags and proofs anyway. Then based on the HTML output it is possible to link footnotes to tags and proofs. This is not very clean, maybe there is a cleaner way of exporting this to a file called `footnotes` which links their id's to filenames where they appear, but I don't see a way to do this, yet.

**Comment by pbelmans** [comment]
I've been experimenting a little.

One not entirely correct solution would be to wrap all footnotes where they appear in an `<aside>`, exactly where they are used. In CSS we'd just hide these, as footnotes are not supposed to be important anyway, and we let JavaScript collect all footnotes on a page and display them on the bottom, and at the same time fix the numbering.

In an ideal world I would just write all footnotes to their own files, and let `gerby-tools` look for links to footnotes. Then we could assign footnotes to tags, but then we'd end up dealing with footnotes appearing in proofs versus footnotes in statements, etc. etc. Also, this wouldn't give the correct numbering.

The JavaScript solution seems to be the most flexible to be honest. Or, we could do this in Flask to make sure the HTML output is good as it is. But a plasTeX solution doesn't seem feasible.

**Comment by chngr** [comment]
Another, perhaps equally spotty solution, would be to render the footnotes where they appear, then use the ``postProcess`` argument in the [``cleanup``](https://github.com/pbelmans/plastex/blob/8ecd79e8273d7eb8231a6e5b4e7bafa3e6e818cf/plasTeX/Renderers/__init__.py#L521-L561) process at the end of rendering to extract out the rendered footnotes.

Something that I have been trying to get work is just simply extract out a rendered form of the footnotes at the end of the rendering process. You can do this at the end of the [``render``](https://github.com/pbelmans/plastex/blob/8ecd79e8273d7eb8231a6e5b4e7bafa3e6e818cf/plasTeX/Renderers/Gerby/__init__.py#L175-L185) method by looking at ``document.userdata["footnotes"]``; each footnote element is stored there by the end of the rendering process. However, I have been unable to figure out how to get plasTeX to process the raw ``TeXFragment`` and give me a rendered string.

**Comment by pbelmans** [comment]
This was implemented in #17. Its output looked good, I'm now implementing things in the website, then we'll see if there are things we have forgotten about.
